/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package readinglistGUI;

import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import readinglist.ReadingListDatabase;

/**
 *
 */
public class AddMangaSeriesPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddMangaSeriesPanel
     */
    public AddMangaSeriesPanel() {
        initComponents();
    }
    public static void main(String[] args){
        GUIController.testPanel(new AddMangaSeriesPanel());
    }
    public boolean validateForm(){
        //make sure everything that isn't optional is filled out
        return true;
    }
    
    public void submitForm(){
        System.out.println("Hello world");
        int[][] authorsAndRoles = this.topLevelAuthorPanel1.getFormData();
        int[] tags = this.chooseTagPanel1.getSelectedTags();
        int publisher = 0;
        int franchise = 0;
        try {
             franchise = this.midFranchisePanel1.getFormFranchise();
             publisher = this.midPublisherPanel1.getFormPublisher();
        } catch (SQLException ex) {
            Logger.getLogger(AddMangaSeriesPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddMangaSeriesPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            this.volumesSpinner.commitEdit();
        } catch (ParseException ex) {
            Logger.getLogger(AddMangaSeriesPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        int numVolumes = (Integer) this.volumesSpinner.getValue();
        
        String title = this.workTitleText.getText();
        String subtitle = this.subtitleText.getText();
        boolean ownCopy = this.ownCheck.isSelected();
        boolean isComplete = this.completeCheck.isSelected();
        String summary = this.summaryArea.getText();
        String notes = this.jTextArea1.getText(); //where is this supposed to go? Series has no notes, and duplicating it in every work is not what user will want, probably
        
        //create the series
        try {
            ReadingListDatabase rld = new ReadingListDatabase();
            int series = rld.createSeries(title, subtitle, summary, !isComplete, notes);
            
            //loop through and create all of the volumes
            for(int i=1; i <= numVolumes; i++ ){
                int work_id = rld.createMangaWork(title, subtitle, i, null, null, ownCopy);
                int link = rld.createLinkWorkSeries(series, work_id);
                //link all the authors and roles to the works
                this.linkAuthorWorks(rld, authorsAndRoles, work_id);
                //link all works to publisher
                rld.createLinkWorksPublisher(work_id, publisher);
                //link all tags to each work
                this.linkTagsWork(rld, work_id, tags);
            }
            
            //link series and franchise
            rld.createLinkSeriesFranchise(series, franchise);
            
            
            
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddMangaSeriesPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
        
    }
    
    public int[] linkAuthorWorks(ReadingListDatabase rld, int[][] authorsAndRoles, int work) throws SQLException{
        int[] output = new int[authorsAndRoles.length];
        for(int i =0; i < authorsAndRoles.length; i++){
            output[i] = linkAuthorWork(rld, authorsAndRoles[i][0], authorsAndRoles[i][1], work);
        }
        return output;
    }
    public int linkAuthorWork(ReadingListDatabase rld, int author, int role, int work) throws SQLException{
        return rld.createLinkAuthorWork(work, author, role, null);
    }
    public int[] linkTagsWork(ReadingListDatabase rld, int work, int[] tags) throws SQLException{
        int[] output = new int[tags.length];
        int i=0;
        for(int tag: tags){
            output[i++] = rld.createLinkTagWork(work, tag);
        }
        return output;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        workTitleText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        subtitleText = new javax.swing.JTextField();
        ownCheck = new javax.swing.JCheckBox();
        completeCheck = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        summaryArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        topLevelAuthorPanel1 = new readinglistGUI.TopLevelAuthorPanel();
        chooseTagPanel1 = new readinglistGUI.ChooseTagPanel();
        midPublisherPanel1 = new readinglistGUI.MidPublisherPanel();
        midFranchisePanel1 = new readinglistGUI.MidFranchisePanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        volumesSpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Create Manga Series"));

        jLabel2.setText("Title of Work:");

        jLabel3.setText("Subtitle:");

        ownCheck.setText("Do you own a copy?");

        completeCheck.setText("Is the series complete? (not ongoing)");

        summaryArea.setColumns(20);
        summaryArea.setRows(5);
        jScrollPane1.setViewportView(summaryArea);

        jLabel4.setText("Summary:");

        topLevelAuthorPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Authors", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        chooseTagPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tags", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        midPublisherPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        midFranchisePanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Notes: ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel5.setText("Number of Volumes:");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.setToolTipText("");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ownCheck)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(subtitleText, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                        .addComponent(workTitleText)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 40, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(completeCheck)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(volumesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addComponent(chooseTagPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(topLevelAuthorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(midPublisherPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(midFranchisePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(workTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(subtitleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(ownCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(completeCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(volumesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addComponent(chooseTagPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(topLevelAuthorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(midPublisherPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(midFranchisePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitButton)
                        .addGap(8, 8, 8)
                        .addComponent(Back)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //validate 
        //TO DO
        //create the work in the database, along with everything else
        if(validateForm()){
            submitForm();
        }
        
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        MainMenu main = new MainMenu();
        GUIController.positionJFrame(main);
        
        
    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private readinglistGUI.ChooseTagPanel chooseTagPanel1;
    private javax.swing.JCheckBox completeCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private readinglistGUI.MidFranchisePanel midFranchisePanel1;
    private readinglistGUI.MidPublisherPanel midPublisherPanel1;
    private javax.swing.JCheckBox ownCheck;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField subtitleText;
    private javax.swing.JTextArea summaryArea;
    private readinglistGUI.TopLevelAuthorPanel topLevelAuthorPanel1;
    private javax.swing.JSpinner volumesSpinner;
    private javax.swing.JTextField workTitleText;
    // End of variables declaration//GEN-END:variables
}
