/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package readinglistGUI;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author yahna
 */
public class ChooseAuthorPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChooseAuthorPanel
     */
    public ChooseAuthorPanel() {
        initComponents();
        //ListModel lm;
        //authorList.setmode
        fillAuthorList();
    }
    
    /**
     * Gets all authors from the database and puts them in the list
     */
    public void fillAuthorList(){
        this.authorList.clearSelection();
        try {
            //this.authorList.getSelectedValuesList();//will need this method later
            readinglist.ReadingListDatabase rld = new readinglist.ReadingListDatabase();
            ResultSet authorsRS = rld.getAllAuthors();
            ArrayList<ComboBoxItem> authorItems = new ArrayList<>();
            while(authorsRS.next()){
                String name = authorsRS.getString("name");
                int id = authorsRS.getInt("id");
                ComboBoxItem cbi = new ComboBoxItem(id, name);
                authorItems.add(cbi);
                
            }
            this.authorList.setListData(authorItems.toArray(new ComboBoxItem[authorItems.size()]));
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ChooseAuthorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public static void main(String[] args){
        JFrame jf = new JFrame();
        jf.add(new ChooseAuthorPanel());
        jf.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        authorList = new javax.swing.JList<>();

        jScrollPane1.setViewportView(authorList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<ComboBoxItem> authorList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
