/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package readinglistGUI;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Component;
import java.sql.SQLException;
import javax.swing.JPanel;
import readinglist.ReadingListDatabase;

/**
 *
 * @author yahna
 */
public class MidAuthorPanel extends javax.swing.JPanel {

    /**
     * Creates new form PickAuthorsPanel
     */
    public MidAuthorPanel() {
        initComponents();
        this.jButton1.doClick();
    }
    public static void main(String args[]){
        GUIController.testPanel(new MidAuthorPanel());
    }
    
    /**
     * Gets the ids for author and label
     * @return array with two items: author id and role id
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public int[] getFormData() throws SQLException, ClassNotFoundException{
        int[] ids = new int[2];
        //if(this.isAncestorOf(addAuthorPanel2)){
        if(addAuthorPanel2.isVisible()){
            //we have to make the author first, then get the id
            ids[0] = this.addAuthorPanel2.createAuthor();
            ids[1] = this.addAuthorPanel2.getRole();
        }
        else{
            ids[0] = this.chooseAuthorPanel1.getAuthor().value;
            ids[1] = this.chooseAuthorPanel1.getRole().value;
        }
        return ids;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        chooseAuthorPanel1 = new readinglistGUI.ChooseAuthorPanel();
        addAuthorPanel2 = new readinglistGUI.AddAuthorPanel();

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.CardLayout());
        jPanel2.add(chooseAuthorPanel1, "card3");
        jPanel2.add(addAuthorPanel2, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void swapAuthorComponents(){
        //System.out.println(jPanel2.getLayout().getClass());
        CardLayout cl = (CardLayout)jPanel2.getLayout();
        //cl.show(jPanel2, authorComponent.getName());
        cl.next(jPanel2);
        //cl.last(jPanel2);
        //swap the components
        /*this.jPanel2.removeAll();//.remove(this.);
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(authorComponent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(authorComponent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        
        this.jPanel2.validate();*/
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //if(this.isAncestorOf(addAuthorPanel2)){
        //System.out.println(chooseAuthorPanel1.isVisible() + " " + addAuthorPanel2.isVisible());
        if(addAuthorPanel2.isVisible()){
            swapAuthorComponents();
            this.jButton1.setText("New Author");
        }
        else{
            swapAuthorComponents();
            this.jButton1.setText("Existing Author");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private readinglistGUI.AddAuthorPanel addAuthorPanel2;
    private readinglistGUI.ChooseAuthorPanel chooseAuthorPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
