/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package readinglistGUI;

import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import readinglist.ReadingListDatabase;

/**
 *
 * @author yahna
 */
public class PublisherPanel extends javax.swing.JPanel {

    /**
     * Creates new form PublisherPanel
     */
    public PublisherPanel() {
        initComponents();
        fillComboBox();
        //this.swapPanel();
    }
    
    public static void main(String args[]){
        GUIController.testPanel(new PublisherPanel());
    }
    
    private void fillComboBox(){
        try {
            ReadingListDatabase rld = new ReadingListDatabase();
            this.jComboBox1.setModel(new DefaultComboBoxModel<>(rld.getAllPublishersForCombo().toArray(new ComboBoxItem[0])));
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PublisherPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void reloadPublishers(){
        fillComboBox();
    }
    public void swapPanel(){
        CardLayout cl = (CardLayout)this.getLayout();
        //cl.show(jPanel2, authorComponent.getName());
        cl.next(this);
    }

    /**
     * Get the id of the publisher the user has created or chosen
     * @return 
     */
    public int getPublisherData() throws ClassNotFoundException, SQLException{
        int id;
        if(this.createPublisherPanel.isVisible()){
            ReadingListDatabase rld = new ReadingListDatabase();
            id = rld.createPublisher(this.jTextField1.getText());
        }
        else{
            id = ((ComboBoxItem)(this.jComboBox1.getSelectedItem())).value;
        }
        return id;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createPublisherPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        choosePublisherPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setLayout(new java.awt.CardLayout());

        createPublisherPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Publisher", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel1.setText("Name: ");

        javax.swing.GroupLayout createPublisherPanelLayout = new javax.swing.GroupLayout(createPublisherPanel);
        createPublisherPanel.setLayout(createPublisherPanelLayout);
        createPublisherPanelLayout.setHorizontalGroup(
            createPublisherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPublisherPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );
        createPublisherPanelLayout.setVerticalGroup(
            createPublisherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPublisherPanelLayout.createSequentialGroup()
                .addGroup(createPublisherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 87, Short.MAX_VALUE))
        );

        add(createPublisherPanel, "card2");

        choosePublisherPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Publisher", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel2.setText("Name: ");

        javax.swing.GroupLayout choosePublisherPanelLayout = new javax.swing.GroupLayout(choosePublisherPanel);
        choosePublisherPanel.setLayout(choosePublisherPanelLayout);
        choosePublisherPanelLayout.setHorizontalGroup(
            choosePublisherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choosePublisherPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        choosePublisherPanelLayout.setVerticalGroup(
            choosePublisherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choosePublisherPanelLayout.createSequentialGroup()
                .addGroup(choosePublisherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 87, Short.MAX_VALUE))
        );

        add(choosePublisherPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel choosePublisherPanel;
    private javax.swing.JPanel createPublisherPanel;
    private javax.swing.JComboBox<ComboBoxItem> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
