/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package readinglistGUI;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author yahna
 */
public class TopLevelAuthorPanel extends javax.swing.JPanel {

    /**
     * Creates new form TopLevelAuthorPanel
     */
    public TopLevelAuthorPanel() {
        initComponents();
    }
    public static void main(String[] args){
        GUIController.testPanel(new TopLevelAuthorPanel());
    }
    
    /**
     * Get the author and role ids in all of the panes
     * @return a 2-dimensional int array containing author-role pairs
     */
    public int[][] getFormData(){
        int totalTabs = this.jTabbedPane1.getTabCount();
        //System.out.println("Total tabs: " + totalTabs);
        int[][] result = new int[totalTabs][2];
        for(int i = 0; i < totalTabs; i++)
        {
           MidAuthorPanel ap = (MidAuthorPanel)(this.jTabbedPane1.getComponentAt(i));
           //System.out.println(this.jTabbedPane1.getTabComponentAt(i));
            try {
                result[i] = ap.getFormData();
            } catch (SQLException ex) {
                Logger.getLogger(TopLevelAuthorPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TopLevelAuthorPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return result;
    }
    
    public void test(){
        int[][] data = this.getFormData();
        for (int i = 0; i < data.length; i++){
            System.out.println(data[i][0] + ": " + data[i][1]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        chooseAuthorsPanel1 = new readinglistGUI.MidAuthorPanel();
        deleteButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        jTabbedPane1.addTab("1", chooseAuthorsPanel1);

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton)
                    .addComponent(addButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(addButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        //code for addButton
        this.jTabbedPane1.addTab(this.jTabbedPane1.getTabCount() + 1 +  "", new MidAuthorPanel());
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        this.jTabbedPane1.removeTabAt(this.jTabbedPane1.getSelectedIndex());
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private readinglistGUI.MidAuthorPanel chooseAuthorsPanel1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
