/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package not_used;

import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import readinglist.ReadingListDatabase;
import readinglistGUI.ComboBoxItem;
import readinglistGUI.GUIController;

/**
 *
 * @author yahna
 */
public class TagPanel extends javax.swing.JPanel {

    /**
     * Creates new form TagPanel
     */
    public TagPanel() {
        initComponents();
        setTags();
    }
     public static void main(String args[]){
        GUIController.testPanel(new TagPanel());
    }
    private void setTags(){
        try {
            ReadingListDatabase rld = new ReadingListDatabase();
            ArrayList<ComboBoxItem> cbl = rld.getAllTagsForCombo();
            rld.disconnect();
            this.jComboBox1.setModel(new DefaultComboBoxModel<>(cbl.toArray(new ComboBoxItem[0])));
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TagPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public int createTagFromData() throws SQLException, ClassNotFoundException{
       String name = this.jTextField1.getText();
       String description = this.jTextField2.getText();
       ReadingListDatabase rld = new ReadingListDatabase();
       int id = rld.createTag(name, description);
       rld.disconnect(); 
       return id;
    }
    
    /**
     * Get the id of the chosen tag, creating it first if necessary
     * @return int
     */
    public int collectData() throws ClassNotFoundException, SQLException{
        if(this.createTagPanel.isVisible()){
            return createTagFromData();
        }
        else{
            return ((ComboBoxItem)this.jComboBox1.getSelectedItem()).value;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        selectTagPanel = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        createTagPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        swapButton = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel3.setText("Choose Tag");

        javax.swing.GroupLayout selectTagPanelLayout = new javax.swing.GroupLayout(selectTagPanel);
        selectTagPanel.setLayout(selectTagPanelLayout);
        selectTagPanelLayout.setHorizontalGroup(
            selectTagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectTagPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        selectTagPanelLayout.setVerticalGroup(
            selectTagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectTagPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectTagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel1.add(selectTagPanel, "card6");

        jLabel1.setText("Name");

        jLabel2.setText("Description");

        javax.swing.GroupLayout createTagPanelLayout = new javax.swing.GroupLayout(createTagPanel);
        createTagPanel.setLayout(createTagPanelLayout);
        createTagPanelLayout.setHorizontalGroup(
            createTagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createTagPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(createTagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(createTagPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createTagPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        createTagPanelLayout.setVerticalGroup(
            createTagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createTagPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(createTagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createTagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(createTagPanel, "card7");

        add(jPanel1);

        swapButton.setText("Switch");
        swapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swapButtonActionPerformed(evt);
            }
        });
        add(swapButton);
    }// </editor-fold>//GEN-END:initComponents

    private void swapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swapButtonActionPerformed
        //System.out.println(jPanel2.getLayout().getClass());
        CardLayout cl = (CardLayout)jPanel1.getLayout();
        //cl.show(jPanel2, authorComponent.getName());
        cl.next(jPanel1);
    }//GEN-LAST:event_swapButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel createTagPanel;
    private javax.swing.JComboBox<ComboBoxItem> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel selectTagPanel;
    private javax.swing.JButton swapButton;
    // End of variables declaration//GEN-END:variables
}
